### ISSUE TITLE
BOT.py运行后提示

### ISSUE THREAD

**Issue by 0769559** [LYshiying/ui_bot#7]
系统debian10
萌新不懂 提示的这请问还有救吗 好像时区相关 但是不知道从哪入手

root@racknerd-ce2ee0:~# cd ui_bot
root@racknerd-ce2ee0:~/ui_bot# python3 bot.py
msgpack not installed, MsgPackSerializer unavailable
WARNING:  Provided reload directories ['bot.py'] did not contain valid directories, watching current working directory.
INFO:     Will watch for changes in these directories: ['/root/ui_bot']
INFO:     Uvicorn running on http://127.0.0.1:9233 (Press CTRL+C to quit)
INFO:     Started reloader process [3883] using statreload
msgpack not installed, MsgPackSerializer unavailable
2022-04-10 23:58:22 | Services:load_config | INFO | 文件清理配置文件成功加载！
[2022-04-10 23:58:22,802 nonebot] INFO: Succeeded to import and load "src.plugins.file_manager"
2022-04-10 23:58:22 | Services:load_config | INFO | bot相关配置文件成功加载！
2022-04-10 23:58:22 | Services:load_config | INFO | pixiv相关配置文件成功加载！
[2022-04-10 23:58:22,981 nonebot] INFO: Succeeded to import and load "src.plugins.pixiv"
2022-04-10 23:58:23 | Services:load_config | INFO | 以图搜图配置文件成功加载！
[2022-04-10 23:58:23,106 nonebot] INFO: Succeeded to import and load "src.plugins.search_image"
2022-04-10 23:58:23 | Services:load_config | INFO | 插件管理器配置文件成功加载！
[2022-04-10 23:58:23,125 nonebot] INFO: Succeeded to import and load "src.plugins.plugin_manager"
2022-04-10 23:58:23 | Services:load_config | INFO | 获取色图配置文件成功加载！
[2022-04-10 23:58:23,143 nonebot] INFO: Succeeded to import and load "src.plugins.setu"
[2022-04-10 23:58:23,144 nonebot] INFO: Succeeded to import and load "src.plugins.bot_manager"
2022-04-10 23:58:23 | Services:load_config | INFO | 60秒看世界配置文件成功加载！
[2022-04-10 23:58:23,172 nonebot] INFO: Succeeded to import and load "src.plugins.60sec"
[2022-04-10 23:58:23,172 nonebot] INFO: Running on 127.0.0.1:19198
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://127.0.0.1:19198 (CTRL + C to quit)
/usr/local/lib/python3.9/dist-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
[2022-04-10 23:58:23,179 nonebot] INFO: Scheduler started
[2022-04-10 23:58:23,180] Running on http://127.0.0.1:19198 (CTRL + C to quit)

![image](https://user-images.githubusercontent.com/22361624/162634204-ce43d44e-9a36-4194-9153-0d90f29c4593.png)

**Comment by shirumesu** [comment]
抱歉 现在才看到！

可能跟时区没关系(不过请确保你的时区是中国时区或者其他你需要的时区 否则pixiv更新检查会乱(原定为中午12:50)
请在根目录用`pip install nonebot[scheduler]`试试，依赖文件中似乎遗漏了这一项
但这个应该不会导致程序结束，请试试私聊bot发个help看看是否有回应

而且没有看到连接上go-cqhttp的提示，请确保你打开go-cqhttp了
选择反向ws连接 yml配置文件中的反向ws链接中 universal 一项应该为`ws://127.0.0.1:19198/ws`，其余两项不用管

**Comment by 0769559** [comment]
> 抱歉 现在才看到！
> 
> 可能跟时区没关系(不过请确保你的时区是中国时区或者其他你需要的时区 否则pixiv更新检查会乱(原定为中午12:50) 请在根目录用`pip install nonebot[scheduler]`试试，依赖文件中似乎遗漏了这一项 但这个应该不会导致程序结束，请试试私聊bot发个help看看是否有回应
> 
> 而且没有看到连接上go-cqhttp的提示，请确保你打开go-cqhttp了 选择反向ws连接 yml配置文件中的反向ws链接中 universal 一项应该为`ws://127.0.0.1:19198/ws`，其余两项不用管


谢谢回复，我重新重置了系统后再逐步安装后启动提示的这个了。

这是我用过的命令和相关的config.py 只关闭了打分（没有api启动时会提示所以关了）
![image](https://user-images.githubusercontent.com/22361624/163038337-46a31bdc-a139-4742-8b68-73c8353de87e.png)
![image](https://user-images.githubusercontent.com/22361624/163038671-452834a8-f922-420c-b1f9-f8132274d743.png)

root@racknerd-ce2ee0:~# cd ui_bot
root@racknerd-ce2ee0:~/ui_bot# python3 bot.py
msgpack not installed, MsgPackSerializer unavailable
WARNING:  Provided reload directories ['bot.py'] did not contain valid directories, watching current working directory.
INFO:     Will watch for changes in these directories: ['/root/ui_bot']
INFO:     Uvicorn running on http://127.0.0.1:9233 (Press CTRL+C to quit)
INFO:     Started reloader process [9294] using statreload
msgpack not installed, MsgPackSerializer unavailable
2022-04-13 03:21:39 | Services:load_config | INFO | 群空调配置文件成功加载！
[2022-04-13 03:21:39,350 nonebot] INFO: Succeeded to import and load "src.plugins.aircon"
2022-04-13 03:21:39 | Services:load_config | INFO | bot相关配置文件成功加载！
2022-04-13 03:21:39 | Services:load_config | INFO | 推特订阅配置文件成功加载！
[2022-04-13 03:21:39,536 nonebot] INFO: Succeeded to import and load "src.plugins.twitter"
2022-04-13 03:21:39 | Services:load_config | INFO | 莫妮卡翻译配置文件成功加载！
[2022-04-13 03:21:39,554 nonebot] INFO: Succeeded to import and load "src.plugins.justmonika"
[2022-04-13 03:21:39,554 nonebot] INFO: Succeeded to import and load "src.plugins.bot_manager"
2022-04-13 03:21:39 | Services:load_config | INFO | 60秒看世界配置文件成功加载！
[2022-04-13 03:21:39,571 nonebot] INFO: Succeeded to import and load "src.plugins.60sec"
2022-04-13 03:21:39 | Services:load_config | INFO | 文件清理配置文件成功加载！
[2022-04-13 03:21:39,591 nonebot] INFO: Succeeded to import and load "src.plugins.file_manager"
2022-04-13 03:21:39 | Services:load_config | INFO | 彩云续写配置文件成功加载！
[2022-04-13 03:21:39,610 nonebot] INFO: Succeeded to import and load "src.plugins.caiyun"
2022-04-13 03:21:39 | Services:load_config | INFO | 表情制作配置文件成功加载！
[2022-04-13 03:21:39,777 nonebot] INFO: Succeeded to import and load "src.plugins.mkmeme"
2022-04-13 03:21:39 | Services:load_config | INFO | 人偶配置文件成功加载！
[2022-04-13 03:21:39,804 nonebot] INFO: Succeeded to import and load "src.plugins.marionette"
2022-04-13 03:21:39 | Services:load_config | INFO | 自定义回复配置文件成功加载！
[2022-04-13 03:21:39,829 nonebot] INFO: Succeeded to import and load "src.plugins.reply_msg"
2022-04-13 03:21:39 | Services:load_config | INFO | 获取色图配置文件成功加载！
[2022-04-13 03:21:39,858 nonebot] INFO: Succeeded to import and load "src.plugins.setu"
2022-04-13 03:21:39 | Services:load_config | INFO | 碧蓝航线wiki配置文件成功加载！
[2022-04-13 03:21:39,984 nonebot] INFO: Succeeded to import and load "src.plugins.blhxwiki"
2022-04-13 03:21:40 | Services:load_config | INFO | 以图搜图配置文件成功加载！
[2022-04-13 03:21:40,165 nonebot] INFO: Succeeded to import and load "src.plugins.search_image"
2022-04-13 03:21:40 | Services:load_config | INFO | 枝江查重配置文件成功加载！
[2022-04-13 03:21:40,187 nonebot] INFO: Succeeded to import and load "src.plugins.zijiang"
2022-04-13 03:21:40 | Services:load_config | INFO | 俄罗斯轮盘配置文件成功加载！
[2022-04-13 03:21:40,209 nonebot] INFO: Succeeded to import and load "src.plugins.russian"
2022-04-13 03:21:40 | Services:load_config | INFO | 使用帮助配置文件成功加载！
[2022-04-13 03:21:40,234 nonebot] INFO: Succeeded to import and load "src.plugins.usage"
2022-04-13 03:21:40 | Services:load_config | INFO | 切噜语翻译配置文件成功加载！
[2022-04-13 03:21:40,256 nonebot] INFO: Succeeded to import and load "src.plugins.cheru"
2022-04-13 03:21:40 | Services:load_config | INFO | 插件管理器配置文件成功加载！
[2022-04-13 03:21:40,285 nonebot] INFO: Succeeded to import and load "src.plugins.plugin_manager"
2022-04-13 03:21:40 | Services:load_config | INFO | pixiv相关配置文件成功加载！
[2022-04-13 03:21:40,326 nonebot] INFO: Succeeded to import and load "src.plugins.pixiv"
[2022-04-13 03:21:40,326 nonebot] INFO: Running on 127.0.0.1:19198
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://127.0.0.1:19198 (CTRL + C to quit)
/usr/local/lib/python3.9/dist-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
[2022-04-13 03:21:40,333 nonebot] INFO: Scheduler started
[2022-04-13 03:21:40,334] Running on http://127.0.0.1:19198 (CTRL + C to quit)
[2022-04-13 03:21:40,453] 127.0.0.1:54624 GET /ws 1.1 101 - 3143
2022-04-13 03:22:39 | __init__:check_multi_update | INFO | 检查推特更新
2022-04-13 03:22:39 | __init__:check_multi_update | INFO | 检查结束,成功0次,失败0次
[2022-04-13 03:23:08,025 nonebot] INFO: Self: 1975583037, Message 1869733369 from 348435932: 'help'
[2022-04-13 03:23:08,028 nonebot] ERROR: An exception occurred while running command ('使用帮助',):
[2022-04-13 03:23:08,028 nonebot] ERROR: module 'config' has no attribute 'DEFAULT_COMMAND_PERMISSION'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/nonebot/command/__init__.py", line 869, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/command/__init__.py", line 119, in run
    has_perm = await self._check_perm(session) if check_perm else True
  File "/usr/local/lib/python3.9/dist-packages/nonebot/command/__init__.py", line 188, in _check_perm
    else session.bot.config.DEFAULT_COMMAND_PERMISSION)
AttributeError: module 'config' has no attribute 'DEFAULT_COMMAND_PERMISSION'
[2022-04-13 03:23:08,038 nonebot] INFO: Message 1869733369 is handled as a command
[2022-04-13 03:23:12,529 nonebot] INFO: Self: 1975583037, Message 410447215 from 348435932: 'bot状态'
[2022-04-13 03:23:12,531 nonebot] ERROR: An exception occurred while running command ('bot状态',):
[2022-04-13 03:23:12,531 nonebot] ERROR: module 'config' has no attribute 'DEFAULT_COMMAND_PERMISSION'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/nonebot/command/__init__.py", line 869, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/command/__init__.py", line 119, in run
    has_perm = await self._check_perm(session) if check_perm else True
  File "/usr/local/lib/python3.9/dist-packages/nonebot/command/__init__.py", line 188, in _check_perm
    else session.bot.config.DEFAULT_COMMAND_PERMISSION)
AttributeError: module 'config' has no attribute 'DEFAULT_COMMAND_PERMISSION'
[2022-04-13 03:23:12,532 nonebot] INFO: Message 410447215 is handled as a command
[2022-04-13 03:23:25,463 nonebot] INFO: Self: 1975583037, Message -2045609780 from 348435932: '123'
2022-04-13 03:23:39 | __init__:check_multi_update | INFO | 检查推特更新
2022-04-13 03:23:39 | __init__:check_multi_update | INFO | 检查结束,成功0次,失败0次
2022-04-13 03:24:39 | __init__:check_multi_update | INFO | 检查推特更新
2022-04-13 03:24:39 | __init__:check_multi_update | INFO | 检查结束,成功0次,失败0次
2022-04-13 03:25:39 | __init__:check_multi_update | INFO | 检查推特更新
2022-04-13 03:25:39 | __init__:check_multi_update | INFO | 检查结束,成功0次,失败0次
2022-04-13 03:26:39 | __init__:check_multi_update | INFO | 检查推特更新
2022-04-13 03:26:39 | __init__:check_multi_update | INFO | 检查结束,成功0次,失败0次
2022-04-13 03:27:39 | __init__:check_multi_update | INFO | 检查推特更新
2022-04-13 03:27:39 | __init__:check_multi_update | INFO | 检查结束,成功0次,失败0次
2022-04-13 03:28:39 | __init__:check_multi_update | INFO | 检查推特更新
2022-04-13 03:28:39 | __init__:check_multi_update | INFO | 检查结束,成功0次,失败0次

**Comment by shirumesu** [comment]
这看着是nonebot的问题，请试试`pip list |grep nonebot`看看是不是1.9.1 如果不是请卸载重新安装试试
`pip uninstall nonebot -y`
`pip install nonebot==1.9.1 -y`

**Comment by 0769559** [comment]
> 这看着是nonebot的问题，请试试`pip list |grep nonebot`看看是不是1.9.1 如果不是请卸载重新安装试试 `pip uninstall nonebot -y` `pip install nonebot==1.9.1 -y`

root@racknerd-ce2ee0:~# pip list |grep nonebot
nonebot               1.9.1
root@racknerd-ce2ee0:~#

**Comment by shirumesu** [comment]
请试试`cat /usr/local/lib/python3.9/dist-packages/nonebot/default_config.py |grep DEFAULT_COMMAND_PERMISSION`
如果没有输出的话请重新安装一下nonebot

如果有输出但是依然报错，那就直接将缺的那一行加入到config.py中吧…
`DEFAULT_COMMAND_PERMISSION = lambda _: True`
位置任意，保证在第二行的`from nonebot.default_config import *`以下就行

~~另外有个不知道该不该说的：仔细看了一眼你好像只用过apt update 没有用过apt upgrade 这两个的区别是前者是查找是否有更新可用，后者才是真正的尝试去更新 不过跟这个问题应该没有什么关系~~

**Comment by 0769559** [comment]
> 请试试`cat /usr/local/lib/python3.9/dist-packages/nonebot/default_config.py |grep DEFAULT_COMMAND_PERMISSION` 如果没有输出的话请重新安装一下nonebot
> 
> 如果有输出但是依然报错，那就直接将缺的那一行加入到config.py中吧… `DEFAULT_COMMAND_PERMISSION = lambda _: True` 位置任意，保证在第二行的`from nonebot.default_config import *`以下就行
> 
> ~另外有个不知道该不该说的：仔细看了一眼你好像只用过apt update 没有用过apt upgrade 这两个的区别是前者是查找是否有更新可用，后者才是真正的尝试去更新 不过跟这个问题应该没有什么关系~


root@racknerd-ce2ee0:~# cat /usr/local/lib/python3.9/dist-packages/nonebot/default_config.py |grep DEFAULT_COMMAND_PERMISSION
DEFAULT_COMMAND_PERMISSION: PermissionPolicy_T = lambda _: True  # EVERYBODY
    'DEFAULT_COMMAND_PERMISSION'
有输出依然报错，请问这config.py是根目录的那个吗？我看里面好像没有from nonebot.default_config import这一行，bot.py里面也是
apt update我看很多在安装之前都会先update然后再装，具体区别还真没深究过

刚刚试着在config把你说的2个都补上后 help指令成功运行没报错了 谢谢
![image](https://user-images.githubusercontent.com/22361624/163542469-b7db7e77-4303-45ca-999c-79772bb267fa.png)

**Comment by 0769559** [comment]
另外我看有人写了个别的bot的一键部署脚本（不过功能不适合我），试过后很简单就能部署起来。感觉可以用起来 以后部署你的机器人就轻松多了
https://github.com/AkashiCoin/zhenxun_bot-deploy

**Comment by shirumesu** [comment]
草……原来是我忘了加在config_sample里…因为平时都是config试完配置可用再加进去的……可能是之前哪次忘记了，抱歉搞的那么麻烦
部署脚本的话，由于我配置文件使用的是py文件，修改上不太方便……
不过也不是完全没有办法，我之后会想办法搞一下的，感谢分享
另外这个issue我就关闭了！

**Comment by 0769559** [comment]
恩 谢谢了~那个部署脚本是nonebot2和需要py的 所以才感觉能给你参考。

“注册群 普通群”是只需要我在要设置的群里发一句这样的指令就可以吗？能不能在配置文件里添加或修改的。

**Comment by shirumesu** [comment]
是的 可以发送`help 插件管理器`(私聊就行)查看对插件的单独管理
你可以修改每个插件中的uiconfig.py中的enable_group那一项然后重启bot，不过注册群这个功能本身就是减少一堆插件单独调整的操作量出来的……
配置文件改的话就改成类似以下形式(去掉括号)
```json
{
    "enable_group": {
        "123456789(群号)": "普通群(亲友群/普通群)"
    }
}
```

**Comment by 0769559** [comment]
> 



> 是的 可以发送`help 插件管理器`(私聊就行)查看对插件的单独管理 你可以修改每个插件中的uiconfig.py中的enable_group那一项然后重启bot，不过注册群这个功能本身就是减少一堆插件单独调整的操作量出来的…… 配置文件改的话就改成类似以下形式(去掉括号)
> 
> ```json
> {
>     "enable_group": {
>         "123456789(群号)": "普通群(亲友群/普通群)"
>     }
> }
> ```

我发现除了除了超级用户私聊机器人外，都会提示的权限不够。请问怎么让机器人里的好友列表都开通亲友群级别的权限？

**Comment by shirumesu** [comment]
这是因为超级用户除非设定了忽略，否则必定通过权限检查
而大部分涉及r18的插件都禁止了私聊使用

至于好友列表可以私聊使用而非好友私聊不行 目前没有这个功能……只有开启是否可以私聊的权限以及拉黑某个用户私聊的权限
不过可以尝试通过qq设置禁止非好友私聊加上允许所有私聊来做到类似功能
qq 设置-消息通知-临时会话设置 然后全部关掉

**Comment by 0769559** [comment]
> 这是因为超级用户除非设定了忽略，否则必定通过权限检查 而大部分涉及r18的插件都禁止了私聊使用
> 
> 至于好友列表可以私聊使用而非好友私聊不行 目前没有这个功能……只有开启是否可以私聊的权限以及拉黑某个用户私聊的权限 不过可以尝试通过qq设置禁止非好友私聊加上允许所有私聊来做到类似功能 qq 设置-消息通知-临时会话设置 然后全部关掉

那超级用户如何设定忽略，或者说如何给指定用户设置权限

**Comment by shirumesu** [comment]
忽略超级用户因为只有我调试的时候才用，所以没有单独设定的选项，要修改的话只能改文件
```python
# 根目录/src/Services.py 464-466行
checker = self.check_perm(
                    session, self, plugin_manager, ignore_superuser
                )
# 改为:
checker = self.check_perm(
                    session, self, plugin_manager, True
                )
```

特定到每个用户的不同权限目前能做的只有拉黑以及取消拉黑该用户的选项，拉黑后不管私聊还是群聊都无法使用任何功能
目前对于一个插件能做的只有四件事
1. 插件启用/禁闭
2. 插件是否允许私聊
3. 插件的群白名单
4. 插件的用户黑名单

也就是 help 插件管理器 里的八个选项了

**Comment by 0769559** [comment]
> 



> 忽略超级用户因为只有我调试的时候才用，所以没有单独设定的选项，要修改的话只能改文件
> 
> ```python
> # 根目录/src/Services.py 464-466行
> checker = self.check_perm(
>                     session, self, plugin_manager, ignore_superuser
>                 )
> # 改为:
> checker = self.check_perm(
>                     session, self, plugin_manager, True
>                 )
> ```
> 
> 特定到每个用户的不同权限目前能做的只有拉黑以及取消拉黑该用户的选项，拉黑后不管私聊还是群聊都无法使用任何功能 目前对于一个插件能做的只有四件事
> 
> 1. 插件启用/禁闭
> 2. 插件是否允许私聊
> 3. 插件的群白名单
> 4. 插件的用户黑名单
> 
> 也就是 help 插件管理器 里的八个选项了

# 根目录/src/Services.py 464-466行
checker = self.check_perm(
                    session, self, plugin_manager, ignore_superuser
                )
# 改为:
checker = self.check_perm(
                    session, self, plugin_manager, True
                )

改为 True后好像是所有人都没权限了，包括超级用户

**Comment by 0769559** [comment]
if checker[0]:
                    logger.debug(
                        f"用户{uid}使用插件{self.name_cn}(cmd:{name})通过: {checker[1]}"
                    )
                    return await func(session, *args, **kw)
                else:
                    logger.info(
                        f"用户{uid}使用插件{self.name_cn}(cmd:{name})不通过: {checker[1]}"
                    )
                    return await func(session, *args, **kw)


把不通过的返回结果改成判断通过时的结果，总算其他用户也能私聊使用了
